name: Simple Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24f3003241@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Verify action
        run: echo "GitHub Actions is working!"
